# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1poAbKG5mN_rV6MGdlmQmw4mXwchHxRyG
"""

import pandas

import numpy

import matplotlib

import seaborn

from google.colab import files
uploaded = files.upload()


import io
import pandas as pd


df = pd.read_csv(io.BytesIO(uploaded['airlines_flights_data.csv']))


df.head()

from google.colab import drive ;drive.mount('/content/drive')



import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/airlines_flights_data.csv')

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/airlines_flights_data.csv')

df.head()

df.describe

df.head()


df.shape


df.columns


df.info()

df.describe()

df.mean(numeric_only=True)


df.std(numeric_only=True)


df['price'].mean()
df['price'].std()

df.isnull().sum()


df.isna().sum()


df[df['price'].isna()].head(4)

df.describe()


df['price'].isnull().sum()


df[df['price'].isna()].head(4)

df.groupby('airline')['price'].median()

#histogram for price
import matplotlib.pyplot as plt

plt.hist(df['price'].dropna(), bins=30, edgecolor='black')
plt.title('Distribution of Flight Prices')
plt.xlabel('Flight Price (₹)')
plt.ylabel('Frequency')
plt.show()

df.groupby('airline')['price'].median()

df.groupby('source_city')['duration'].mean()

df.groupby('class')['price'].describe()

from google.colab import files
import io
import pandas as pd
import matplotlib.pyplot as plt

uploaded = files.upload()
df = pd.read_csv(io.BytesIO(uploaded['airlines_flights_data.csv']))


print("Shape of dataset:", df.shape)
print("\nColumns:", df.columns.tolist())
print("\nData types:")
print(df.info())
print("\nSummary statistics:")
print(df.describe())

print("\nMissing values per column:")
print(df.isnull().sum())


print("\nRows with missing prices:")
print(df[df['price'].isna()].head(4))


print("\nMedian price by airline:")
print(df.groupby('airline')['price'].median())
plt.figure(figsize=(8,5))
plt.hist(df['price'].dropna(), bins=30, edgecolor='black')
plt.title('Distribution of Flight Prices')
plt.xlabel('Price (₹)')
plt.ylabel('Frequency')
plt.show()


df['price'].fillna(df['price'].mean(), inplace=True)


print("\nAfter handling missing values:")
print(df.isnull().sum())

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(6,4))
sns.heatmap(df[['duration', 'days_left', 'price']].corr(), annot=True, cmap='Blues')
plt.title('Correlation Heatmap')
plt.show()



plt.figure(figsize=(10,5))
sns.boxplot(x='airline', y='price', data=df)
plt.title('Flight Price Distribution by Airline')
plt.xticks(rotation=45)
plt.show()



plt.figure(figsize=(6,4))
sns.boxplot(x='class', y='price', data=df)
plt.title('Price Comparison by Ticket Class')
plt.show()



avg_price_by_days = df.groupby('days_left')['price'].mean()

plt.figure(figsize=(8,4))
avg_price_by_days.plot(kind='line', marker='o')
plt.title('Average Flight Price vs. Days Left for Departure')
plt.xlabel('Days Left')
plt.ylabel('Average Price (₹)')
plt.grid(True)
plt.show()

sns.histplot(df['Income'], kde=True, color='green')